-- Generated by formal/generate_grouping.py; finite claims are kernel-checked.
import Chair.Tiling

namespace Chair.GroupingData

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false

abbrev ContactId := Fin 44
abbrev FaceId := Fin 24

def contactOrientation (i : Fin 44) : Fin 24 := match i.val with
  | 0 => 23
  | 1 => 10
  | 2 => 17
  | 3 => 4
  | 4 => 5
  | 5 => 6
  | 6 => 22
  | 7 => 17
  | 8 => 1
  | 9 => 16
  | 10 => 14
  | 11 => 22
  | 12 => 0
  | 13 => 20
  | 14 => 11
  | 15 => 19
  | 16 => 0
  | 17 => 20
  | 18 => 11
  | 19 => 19
  | 20 => 13
  | 21 => 6
  | 22 => 1
  | 23 => 16
  | 24 => 14
  | 25 => 22
  | 26 => 9
  | 27 => 7
  | 28 => 12
  | 29 => 1
  | 30 => 11
  | 31 => 1
  | 32 => 16
  | 33 => 14
  | 34 => 22
  | 35 => 9
  | 36 => 7
  | 37 => 5
  | 38 => 3
  | 39 => 12
  | 40 => 23
  | 41 => 10
  | 42 => 17
  | 43 => 4
  | _ => 23

def contactShift (i : Fin 44) : V3 := match i.val with
  | 0 => ⟨-2, 0, 0⟩
  | 1 => ⟨-2, 0, 0⟩
  | 2 => ⟨-2, 0, 0⟩
  | 3 => ⟨-2, 0, 0⟩
  | 4 => ⟨-1, -1, -1⟩
  | 5 => ⟨-1, -1, 1⟩
  | 6 => ⟨-1, 1, -1⟩
  | 7 => ⟨-1, 1, 1⟩
  | 8 => ⟨0, -2, 0⟩
  | 9 => ⟨0, -2, 0⟩
  | 10 => ⟨0, -2, 0⟩
  | 11 => ⟨0, -2, 0⟩
  | 12 => ⟨0, 0, -2⟩
  | 13 => ⟨0, 0, -2⟩
  | 14 => ⟨0, 0, -2⟩
  | 15 => ⟨0, 0, -2⟩
  | 16 => ⟨0, 0, 2⟩
  | 17 => ⟨0, 0, 2⟩
  | 18 => ⟨0, 0, 2⟩
  | 19 => ⟨0, 0, 2⟩
  | 20 => ⟨0, 0, 2⟩
  | 21 => ⟨0, 0, 2⟩
  | 22 => ⟨0, 2, 0⟩
  | 23 => ⟨0, 2, 0⟩
  | 24 => ⟨0, 2, 0⟩
  | 25 => ⟨0, 2, 0⟩
  | 26 => ⟨0, 2, 0⟩
  | 27 => ⟨0, 2, 0⟩
  | 28 => ⟨1, -1, -1⟩
  | 29 => ⟨1, -1, 1⟩
  | 30 => ⟨1, 1, -1⟩
  | 31 => ⟨1, 1, 1⟩
  | 32 => ⟨1, 1, 1⟩
  | 33 => ⟨1, 1, 1⟩
  | 34 => ⟨1, 1, 1⟩
  | 35 => ⟨1, 1, 1⟩
  | 36 => ⟨1, 1, 1⟩
  | 37 => ⟨1, 1, 1⟩
  | 38 => ⟨2, 0, 0⟩
  | 39 => ⟨2, 0, 0⟩
  | 40 => ⟨2, 0, 0⟩
  | 41 => ⟨2, 0, 0⟩
  | 42 => ⟨2, 0, 0⟩
  | 43 => ⟨2, 0, 0⟩
  | _ => ⟨-2, 0, 0⟩

theorem rotation_mem (r : Fin 24) : rotation r ∈ rotations := by
  exact List.getElem_mem (by simpa only [rotations_length] using r.isLt)

def contactMotion (i : ContactId) : GridMotion :=
  ⟨contactShift i, ⟨rotation (contactOrientation i), rotation_mem _⟩⟩

def faceIndex (i : Fin 24) : Fin 24 := match i.val with
  | 0 => 0
  | 1 => 3
  | 2 => 6
  | 3 => 9
  | 4 => 1
  | 5 => 4
  | 6 => 2
  | 7 => 5
  | 8 => 8
  | 9 => 12
  | 10 => 7
  | 11 => 11
  | 12 => 10
  | 13 => 14
  | 14 => 17
  | 15 => 15
  | 16 => 19
  | 17 => 18
  | 18 => 22
  | 19 => 23
  | 20 => 21
  | 21 => 13
  | 22 => 16
  | 23 => 20
  | _ => 0

private theorem cached_face_length : cachedFine.faces.length = 24 := by decide +kernel

def contactFace (f : FaceId) : Face :=
  cachedFine.faces[(faceIndex f).val]'(by rw [cached_face_length]; exact (faceIndex f).isLt)

theorem contactFace_mem (f : FaceId) : contactFace f ∈ fine.faces := by
  rw [fine_eq_cached]
  exact List.getElem_mem _

def faceOptions (i : Fin 24) : List ContactId := match i.val with
  | 0 => [0, 4]
  | 1 => [0, 1, 2, 3, 5]
  | 2 => [0, 1, 2, 3, 6]
  | 3 => [0, 1, 2, 3, 7]
  | 4 => [4, 11]
  | 5 => [5, 8, 9, 10, 11]
  | 6 => [4, 15]
  | 7 => [5, 16, 17, 18, 19, 20, 21]
  | 8 => [6, 12, 13, 14, 15]
  | 9 => [7, 16, 17, 18, 19, 20, 21]
  | 10 => [6, 22, 23, 24, 25, 26, 27]
  | 11 => [7, 22, 23, 24, 25, 26, 27]
  | 12 => [31, 32, 33, 34, 35, 36, 37]
  | 13 => [8, 9, 10, 11, 28]
  | 14 => [8, 9, 10, 11, 29]
  | 15 => [12, 13, 14, 15, 28]
  | 16 => [16, 17, 18, 19, 20, 21, 29]
  | 17 => [31, 32, 33, 34, 35, 36, 37]
  | 18 => [12, 13, 14, 15, 30]
  | 19 => [31, 32, 33, 34, 35, 36, 37]
  | 20 => [22, 23, 24, 25, 26, 27, 30]
  | 21 => [28, 38, 39, 40, 41, 42, 43]
  | 22 => [29, 38, 39, 40, 41, 42, 43]
  | 23 => [30, 38, 39, 40, 41, 42, 43]
  | _ => [0, 4]

def covers (i : ContactId) (f : FaceId) : Bool := (faceOptions f).contains i

private theorem covers_checked : ∀ i : ContactId, ∀ f : FaceId,
    covers i f = ((placed (contactMotion i)).faces.any (fun b => opposed (contactFace f) b zero)) := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

theorem covers_iff (i : ContactId) (f : FaceId) : covers i f = true ↔
    ∃ b ∈ (placed (contactMotion i)).faces, Opposed (contactFace f) b zero := by
  rw [covers_checked]
  simp only [List.any_eq_true, opposed_eq_true]

def pairWitness0 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => some (.overlap 1 6)
  | 2 => some (.overlap 1 5)
  | 3 => some (.overlap 1 3)
  | 4 => some (.overlap 0 3)
  | 5 => some (.overlap 4 3)
  | 6 => some (.overlap 2 6)
  | 7 => some (.overlap 6 5)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness1 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => some (.overlap 1 6)
  | 1 => none
  | 2 => some (.overlap 0 0)
  | 3 => some (.overlap 0 0)
  | 4 => some (.mismatch 10 11)
  | 5 => some (.overlap 5 3)
  | 6 => some (.overlap 3 6)
  | 7 => some (.overlap 1 5)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => some (.overlap 1 6)

def pairWitness2 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => some (.overlap 1 5)
  | 1 => some (.overlap 0 0)
  | 2 => none
  | 3 => some (.overlap 0 0)
  | 4 => none
  | 5 => some (.overlap 3 3)
  | 6 => some (.overlap 6 6)
  | 7 => some (.overlap 2 5)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => some (.overlap 1 5)

def pairWitness3 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => some (.overlap 1 3)
  | 1 => some (.overlap 0 0)
  | 2 => some (.overlap 0 0)
  | 3 => none
  | 4 => some (.mismatch 10 9)
  | 5 => some (.overlap 6 3)
  | 6 => some (.overlap 5 6)
  | 7 => some (.overlap 4 5)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => some (.overlap 1 3)

def pairWitness4 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => some (.overlap 3 0)
  | 1 => some (.mismatch 9 23)
  | 2 => none
  | 3 => some (.mismatch 9 10)
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => some (.mismatch 16 18)
  | 10 => some (.mismatch 16 23)
  | 11 => some (.overlap 5 0)
  | 12 => some (.mismatch 20 10)
  | 13 => some (.mismatch 20 18)
  | 14 => none
  | 15 => some (.overlap 6 0)
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => some (.overlap 3 0)

def pairWitness5 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => some (.overlap 3 4)
  | 1 => some (.overlap 3 5)
  | 2 => some (.overlap 3 3)
  | 3 => some (.overlap 3 6)
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => some (.overlap 6 6)
  | 9 => some (.overlap 6 3)
  | 10 => some (.overlap 6 5)
  | 11 => some (.overlap 6 4)
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 5 6)
  | 17 => some (.overlap 5 3)
  | 18 => some (.overlap 5 5)
  | 19 => some (.overlap 5 4)
  | 20 => some (.overlap 5 1)
  | 21 => some (.overlap 5 2)
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => some (.overlap 3 4)

def pairWitness6 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => some (.overlap 6 2)
  | 1 => some (.overlap 6 3)
  | 2 => some (.overlap 6 6)
  | 3 => some (.overlap 6 5)
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => some (.overlap 3 5)
  | 13 => some (.overlap 3 6)
  | 14 => some (.overlap 3 3)
  | 15 => some (.overlap 3 2)
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => some (.overlap 5 5)
  | 23 => some (.overlap 5 6)
  | 24 => some (.overlap 5 3)
  | 25 => some (.overlap 5 2)
  | 26 => some (.overlap 5 4)
  | 27 => some (.overlap 5 1)
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => some (.overlap 6 2)

def pairWitness7 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => some (.overlap 5 6)
  | 1 => some (.overlap 5 1)
  | 2 => some (.overlap 5 2)
  | 3 => some (.overlap 5 4)
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 3 4)
  | 17 => some (.overlap 3 2)
  | 18 => some (.overlap 3 1)
  | 19 => some (.overlap 3 6)
  | 20 => some (.overlap 3 5)
  | 21 => some (.overlap 3 3)
  | 22 => some (.overlap 6 4)
  | 23 => some (.overlap 6 2)
  | 24 => some (.overlap 6 1)
  | 25 => some (.overlap 6 6)
  | 26 => some (.overlap 6 5)
  | 27 => some (.overlap 6 3)
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => some (.mismatch 7 20)
  | 32 => some (.mismatch 7 11)
  | 33 => some (.mismatch 7 19)
  | 34 => some (.mismatch 7 15)
  | 35 => some (.mismatch 7 4)
  | 36 => some (.mismatch 7 6)
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => some (.overlap 5 6)

def pairWitness8 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => some (.overlap 6 6)
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => some (.overlap 0 0)
  | 10 => some (.overlap 0 0)
  | 11 => some (.overlap 1 3)
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 3 3)
  | 29 => some (.overlap 2 5)
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness9 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => some (.mismatch 10 19)
  | 5 => some (.overlap 3 6)
  | 6 => none
  | 7 => none
  | 8 => some (.overlap 0 0)
  | 9 => none
  | 10 => some (.overlap 0 0)
  | 11 => some (.overlap 1 5)
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 5 3)
  | 29 => some (.overlap 1 5)
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness10 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => some (.mismatch 10 17)
  | 5 => some (.overlap 5 6)
  | 6 => none
  | 7 => none
  | 8 => some (.overlap 0 0)
  | 9 => some (.overlap 0 0)
  | 10 => none
  | 11 => some (.overlap 1 6)
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 6 3)
  | 29 => some (.overlap 4 5)
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness11 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => some (.overlap 0 5)
  | 5 => some (.overlap 4 6)
  | 6 => none
  | 7 => none
  | 8 => some (.overlap 1 3)
  | 9 => some (.overlap 1 5)
  | 10 => some (.overlap 1 6)
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 1 3)
  | 29 => some (.overlap 5 5)
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness12 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => some (.mismatch 10 20)
  | 5 => none
  | 6 => some (.overlap 5 3)
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => some (.overlap 0 0)
  | 14 => some (.overlap 0 0)
  | 15 => some (.overlap 1 3)
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 3 6)
  | 29 => none
  | 30 => some (.overlap 1 5)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness13 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => some (.mismatch 10 22)
  | 5 => none
  | 6 => some (.overlap 6 3)
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => some (.overlap 0 0)
  | 13 => none
  | 14 => some (.overlap 0 0)
  | 15 => some (.overlap 1 5)
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 5 6)
  | 29 => none
  | 30 => some (.overlap 4 5)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness14 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => some (.overlap 3 3)
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => some (.overlap 0 0)
  | 13 => some (.overlap 0 0)
  | 14 => none
  | 15 => some (.overlap 1 6)
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 6 6)
  | 29 => none
  | 30 => some (.overlap 2 5)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness15 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => some (.overlap 0 6)
  | 5 => none
  | 6 => some (.overlap 2 3)
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => some (.overlap 1 3)
  | 13 => some (.overlap 1 5)
  | 14 => some (.overlap 1 6)
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 1 6)
  | 29 => none
  | 30 => some (.overlap 3 5)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness16 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => some (.overlap 6 5)
  | 6 => none
  | 7 => some (.overlap 4 3)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => some (.overlap 0 0)
  | 18 => some (.overlap 0 0)
  | 19 => some (.overlap 1 3)
  | 20 => some (.overlap 1 6)
  | 21 => some (.overlap 1 5)
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.overlap 2 6)
  | 30 => none
  | 31 => some (.overlap 0 4)
  | 32 => some (.overlap 0 2)
  | 33 => some (.overlap 0 1)
  | 34 => some (.overlap 0 6)
  | 35 => some (.overlap 0 5)
  | 36 => some (.overlap 0 3)
  | 37 => some (.overlap 0 1)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness17 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => some (.overlap 3 5)
  | 6 => none
  | 7 => some (.overlap 2 3)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 0 0)
  | 17 => none
  | 18 => some (.overlap 0 0)
  | 19 => some (.overlap 1 5)
  | 20 => some (.overlap 1 3)
  | 21 => some (.overlap 1 6)
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.overlap 1 6)
  | 30 => none
  | 31 => some (.overlap 0 4)
  | 32 => some (.overlap 0 2)
  | 33 => some (.overlap 0 1)
  | 34 => some (.overlap 0 6)
  | 35 => some (.overlap 0 5)
  | 36 => some (.overlap 0 3)
  | 37 => some (.overlap 0 1)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness18 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => some (.overlap 5 5)
  | 6 => none
  | 7 => some (.overlap 1 3)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 0 0)
  | 17 => some (.overlap 0 0)
  | 18 => none
  | 19 => some (.overlap 1 6)
  | 20 => some (.overlap 1 5)
  | 21 => some (.overlap 1 3)
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.overlap 4 6)
  | 30 => none
  | 31 => some (.overlap 0 4)
  | 32 => some (.overlap 0 2)
  | 33 => some (.overlap 0 1)
  | 34 => some (.overlap 0 6)
  | 35 => some (.overlap 0 5)
  | 36 => some (.overlap 0 3)
  | 37 => some (.overlap 0 1)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness19 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => some (.overlap 4 5)
  | 6 => none
  | 7 => some (.overlap 6 3)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 1 3)
  | 17 => some (.overlap 1 5)
  | 18 => some (.overlap 1 6)
  | 19 => none
  | 20 => some (.overlap 0 0)
  | 21 => some (.overlap 0 0)
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.overlap 5 6)
  | 30 => none
  | 31 => some (.mismatch 10 15)
  | 32 => some (.mismatch 10 6)
  | 33 => some (.mismatch 10 4)
  | 34 => some (.mismatch 10 20)
  | 35 => some (.mismatch 10 19)
  | 36 => some (.mismatch 10 11)
  | 37 => some (.mismatch 10 5)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness20 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => some (.overlap 1 5)
  | 6 => none
  | 7 => some (.overlap 5 3)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 1 6)
  | 17 => some (.overlap 1 3)
  | 18 => some (.overlap 1 5)
  | 19 => some (.overlap 0 0)
  | 20 => none
  | 21 => some (.overlap 0 0)
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.overlap 3 6)
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => some (.mismatch 10 4)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness21 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => some (.overlap 2 5)
  | 6 => none
  | 7 => some (.overlap 3 3)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 1 5)
  | 17 => some (.overlap 1 6)
  | 18 => some (.overlap 1 3)
  | 19 => some (.overlap 0 0)
  | 20 => some (.overlap 0 0)
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.overlap 6 6)
  | 30 => none
  | 31 => some (.mismatch 10 13)
  | 32 => some (.mismatch 10 7)
  | 33 => some (.mismatch 10 5)
  | 34 => some (.mismatch 10 22)
  | 35 => some (.mismatch 10 17)
  | 36 => some (.mismatch 10 9)
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness22 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => some (.overlap 5 5)
  | 7 => some (.overlap 4 6)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => some (.overlap 0 0)
  | 24 => some (.overlap 0 0)
  | 25 => some (.overlap 1 3)
  | 26 => some (.overlap 1 6)
  | 27 => some (.overlap 1 5)
  | 28 => none
  | 29 => none
  | 30 => some (.overlap 1 3)
  | 31 => none
  | 32 => some (.mismatch 0 18)
  | 33 => some (.mismatch 0 23)
  | 34 => some (.overlap 0 0)
  | 35 => some (.overlap 0 0)
  | 36 => some (.overlap 0 0)
  | 37 => some (.overlap 0 2)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness23 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => some (.overlap 6 5)
  | 7 => some (.overlap 2 6)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => some (.overlap 0 0)
  | 23 => none
  | 24 => some (.overlap 0 0)
  | 25 => some (.overlap 1 5)
  | 26 => some (.overlap 1 3)
  | 27 => some (.overlap 1 6)
  | 28 => none
  | 29 => none
  | 30 => some (.overlap 4 3)
  | 31 => some (.mismatch 0 23)
  | 32 => none
  | 33 => some (.mismatch 0 18)
  | 34 => some (.overlap 0 0)
  | 35 => some (.overlap 0 0)
  | 36 => some (.overlap 0 0)
  | 37 => some (.overlap 0 2)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness24 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => some (.overlap 3 5)
  | 7 => some (.overlap 1 6)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => some (.overlap 0 0)
  | 23 => some (.overlap 0 0)
  | 24 => none
  | 25 => some (.overlap 1 6)
  | 26 => some (.overlap 1 5)
  | 27 => some (.overlap 1 3)
  | 28 => none
  | 29 => none
  | 30 => some (.overlap 2 3)
  | 31 => some (.mismatch 0 18)
  | 32 => some (.mismatch 0 23)
  | 33 => none
  | 34 => some (.overlap 0 0)
  | 35 => some (.overlap 0 0)
  | 36 => some (.overlap 0 0)
  | 37 => some (.overlap 0 2)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness25 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => some (.overlap 2 5)
  | 7 => some (.overlap 6 6)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => some (.overlap 1 3)
  | 23 => some (.overlap 1 5)
  | 24 => some (.overlap 1 6)
  | 25 => none
  | 26 => some (.overlap 0 0)
  | 27 => some (.overlap 0 0)
  | 28 => none
  | 29 => none
  | 30 => some (.overlap 3 3)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => some (.mismatch 10 2)
  | 36 => some (.mismatch 10 1)
  | 37 => none
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness26 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => some (.overlap 4 5)
  | 7 => some (.overlap 5 6)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => some (.overlap 1 6)
  | 23 => some (.overlap 1 3)
  | 24 => some (.overlap 1 5)
  | 25 => some (.overlap 0 0)
  | 26 => none
  | 27 => some (.overlap 0 0)
  | 28 => none
  | 29 => none
  | 30 => some (.overlap 6 3)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => some (.mismatch 10 1)
  | 35 => none
  | 36 => some (.mismatch 10 2)
  | 37 => some (.mismatch 10 7)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness27 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => some (.overlap 1 5)
  | 7 => some (.overlap 3 6)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => some (.overlap 1 5)
  | 23 => some (.overlap 1 6)
  | 24 => some (.overlap 1 3)
  | 25 => some (.overlap 0 0)
  | 26 => some (.overlap 0 0)
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => some (.overlap 5 3)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => some (.mismatch 10 2)
  | 35 => some (.mismatch 10 1)
  | 36 => none
  | 37 => some (.mismatch 10 6)
  | 38 => none
  | 39 => none
  | 40 => none
  | 41 => none
  | 42 => none
  | 43 => none
  | _ => none

def pairWitness28 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => some (.overlap 3 3)
  | 9 => some (.overlap 3 5)
  | 10 => some (.overlap 3 6)
  | 11 => some (.overlap 3 1)
  | 12 => some (.overlap 6 3)
  | 13 => some (.overlap 6 5)
  | 14 => some (.overlap 6 6)
  | 15 => some (.overlap 6 1)
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => none
  | 38 => some (.overlap 5 4)
  | 39 => some (.overlap 5 2)
  | 40 => some (.overlap 5 1)
  | 41 => some (.overlap 5 6)
  | 42 => some (.overlap 5 5)
  | 43 => some (.overlap 5 3)
  | _ => none

def pairWitness29 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => some (.overlap 5 2)
  | 9 => some (.overlap 5 1)
  | 10 => some (.overlap 5 4)
  | 11 => some (.overlap 5 5)
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 6 2)
  | 17 => some (.overlap 6 1)
  | 18 => some (.overlap 6 4)
  | 19 => some (.overlap 6 5)
  | 20 => some (.overlap 6 3)
  | 21 => some (.overlap 6 6)
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => some (.mismatch 11 4)
  | 32 => some (.mismatch 7 2)
  | 33 => some (.mismatch 7 0)
  | 34 => some (.mismatch 11 11)
  | 35 => some (.mismatch 11 20)
  | 36 => some (.mismatch 11 19)
  | 37 => none
  | 38 => some (.overlap 3 6)
  | 39 => some (.overlap 3 3)
  | 40 => some (.overlap 3 5)
  | 41 => some (.overlap 3 4)
  | 42 => some (.overlap 3 1)
  | 43 => some (.overlap 3 2)
  | _ => none

def pairWitness30 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => some (.overlap 5 1)
  | 13 => some (.overlap 5 4)
  | 14 => some (.overlap 5 2)
  | 15 => some (.overlap 5 3)
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => some (.overlap 3 1)
  | 23 => some (.overlap 3 4)
  | 24 => some (.overlap 3 2)
  | 25 => some (.overlap 3 3)
  | 26 => some (.overlap 3 6)
  | 27 => some (.overlap 3 5)
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => some (.mismatch 7 12)
  | 32 => some (.mismatch 7 16)
  | 33 => some (.mismatch 7 21)
  | 34 => some (.mismatch 7 3)
  | 35 => some (.mismatch 7 8)
  | 36 => some (.mismatch 7 14)
  | 37 => none
  | 38 => some (.overlap 6 5)
  | 39 => some (.overlap 6 6)
  | 40 => some (.overlap 6 3)
  | 41 => some (.overlap 6 2)
  | 42 => some (.overlap 6 4)
  | 43 => some (.overlap 6 1)
  | _ => none

def pairWitness31 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => some (.mismatch 13 11)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 4 0)
  | 17 => some (.overlap 4 0)
  | 18 => some (.overlap 4 0)
  | 19 => some (.mismatch 13 23)
  | 20 => none
  | 21 => some (.mismatch 13 10)
  | 22 => none
  | 23 => some (.mismatch 10 1)
  | 24 => some (.mismatch 10 2)
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.mismatch 4 11)
  | 30 => some (.mismatch 5 21)
  | 31 => none
  | 32 => some (.overlap 0 0)
  | 33 => some (.overlap 0 0)
  | 34 => some (.overlap 1 3)
  | 35 => some (.overlap 1 6)
  | 36 => some (.overlap 1 5)
  | 37 => some (.overlap 0 5)
  | 38 => none
  | 39 => some (.mismatch 3 18)
  | 40 => some (.mismatch 3 23)
  | 41 => some (.overlap 1 0)
  | 42 => some (.overlap 1 0)
  | 43 => some (.overlap 1 0)
  | _ => none

def pairWitness32 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => some (.mismatch 7 11)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 2 0)
  | 17 => some (.overlap 2 0)
  | 18 => some (.overlap 2 0)
  | 19 => some (.mismatch 6 10)
  | 20 => none
  | 21 => some (.mismatch 6 18)
  | 22 => some (.mismatch 10 2)
  | 23 => none
  | 24 => some (.mismatch 10 1)
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.mismatch 2 7)
  | 30 => some (.mismatch 13 21)
  | 31 => some (.overlap 0 0)
  | 32 => none
  | 33 => some (.overlap 0 0)
  | 34 => some (.overlap 1 5)
  | 35 => some (.overlap 1 3)
  | 36 => some (.overlap 1 6)
  | 37 => some (.overlap 0 5)
  | 38 => none
  | 39 => some (.mismatch 13 23)
  | 40 => some (.mismatch 13 10)
  | 41 => some (.overlap 4 0)
  | 42 => some (.overlap 4 0)
  | 43 => some (.overlap 4 0)
  | _ => none

def pairWitness33 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => some (.mismatch 5 11)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 1 0)
  | 17 => some (.overlap 1 0)
  | 18 => some (.overlap 1 0)
  | 19 => some (.mismatch 3 18)
  | 20 => none
  | 21 => some (.mismatch 3 23)
  | 22 => some (.mismatch 10 1)
  | 23 => some (.mismatch 10 2)
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => none
  | 29 => some (.mismatch 0 7)
  | 30 => some (.mismatch 7 21)
  | 31 => some (.overlap 0 0)
  | 32 => some (.overlap 0 0)
  | 33 => none
  | 34 => some (.overlap 1 6)
  | 35 => some (.overlap 1 5)
  | 36 => some (.overlap 1 3)
  | 37 => some (.overlap 0 5)
  | 38 => none
  | 39 => some (.mismatch 6 10)
  | 40 => some (.mismatch 6 18)
  | 41 => some (.overlap 2 0)
  | 42 => some (.overlap 2 0)
  | 43 => some (.overlap 2 0)
  | _ => none

def pairWitness34 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => some (.mismatch 15 7)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 6 0)
  | 17 => some (.overlap 6 0)
  | 18 => some (.overlap 6 0)
  | 19 => some (.mismatch 20 10)
  | 20 => none
  | 21 => some (.mismatch 20 18)
  | 22 => some (.overlap 0 0)
  | 23 => some (.overlap 0 0)
  | 24 => some (.overlap 0 0)
  | 25 => none
  | 26 => some (.mismatch 0 23)
  | 27 => some (.mismatch 0 18)
  | 28 => none
  | 29 => some (.mismatch 11 11)
  | 30 => some (.mismatch 3 7)
  | 31 => some (.overlap 1 3)
  | 32 => some (.overlap 1 5)
  | 33 => some (.overlap 1 6)
  | 34 => none
  | 35 => some (.overlap 0 0)
  | 36 => some (.overlap 0 0)
  | 37 => some (.overlap 0 2)
  | 38 => none
  | 39 => some (.mismatch 9 23)
  | 40 => some (.mismatch 9 10)
  | 41 => some (.overlap 3 0)
  | 42 => some (.overlap 3 0)
  | 43 => some (.overlap 3 0)
  | _ => none

def pairWitness35 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => some (.mismatch 1 21)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 5 0)
  | 17 => some (.overlap 5 0)
  | 18 => some (.overlap 5 0)
  | 19 => some (.mismatch 16 18)
  | 20 => none
  | 21 => some (.mismatch 16 23)
  | 22 => some (.overlap 0 0)
  | 23 => some (.overlap 0 0)
  | 24 => some (.overlap 0 0)
  | 25 => some (.mismatch 0 18)
  | 26 => none
  | 27 => some (.mismatch 0 23)
  | 28 => none
  | 29 => some (.mismatch 16 21)
  | 30 => some (.mismatch 2 11)
  | 31 => some (.overlap 1 6)
  | 32 => some (.overlap 1 3)
  | 33 => some (.overlap 1 5)
  | 34 => some (.overlap 0 0)
  | 35 => none
  | 36 => some (.overlap 0 0)
  | 37 => some (.overlap 0 2)
  | 38 => none
  | 39 => some (.mismatch 20 10)
  | 40 => some (.mismatch 20 18)
  | 41 => some (.overlap 6 0)
  | 42 => some (.overlap 6 0)
  | 43 => some (.overlap 6 0)
  | _ => none

def pairWitness36 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => some (.mismatch 0 21)
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 3 0)
  | 17 => some (.overlap 3 0)
  | 18 => some (.overlap 3 0)
  | 19 => some (.mismatch 9 23)
  | 20 => none
  | 21 => some (.mismatch 9 10)
  | 22 => some (.overlap 0 0)
  | 23 => some (.overlap 0 0)
  | 24 => some (.overlap 0 0)
  | 25 => some (.mismatch 0 23)
  | 26 => some (.mismatch 0 18)
  | 27 => none
  | 28 => none
  | 29 => some (.mismatch 12 21)
  | 30 => some (.mismatch 1 11)
  | 31 => some (.overlap 1 5)
  | 32 => some (.overlap 1 6)
  | 33 => some (.overlap 1 3)
  | 34 => some (.overlap 0 0)
  | 35 => some (.overlap 0 0)
  | 36 => none
  | 37 => some (.overlap 0 2)
  | 38 => none
  | 39 => some (.mismatch 16 18)
  | 40 => some (.mismatch 16 23)
  | 41 => some (.overlap 5 0)
  | 42 => some (.overlap 5 0)
  | 43 => some (.overlap 5 0)
  | _ => none

def pairWitness37 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => some (.overlap 1 0)
  | 17 => some (.overlap 1 0)
  | 18 => some (.overlap 1 0)
  | 19 => some (.mismatch 3 23)
  | 20 => some (.mismatch 3 18)
  | 21 => none
  | 22 => some (.overlap 2 0)
  | 23 => some (.overlap 2 0)
  | 24 => some (.overlap 2 0)
  | 25 => none
  | 26 => some (.mismatch 6 18)
  | 27 => some (.mismatch 6 10)
  | 28 => none
  | 29 => none
  | 30 => none
  | 31 => some (.overlap 0 5)
  | 32 => some (.overlap 0 6)
  | 33 => some (.overlap 0 3)
  | 34 => some (.overlap 0 2)
  | 35 => some (.overlap 0 4)
  | 36 => some (.overlap 0 1)
  | 37 => none
  | 38 => some (.mismatch 13 10)
  | 39 => none
  | 40 => some (.mismatch 13 23)
  | 41 => some (.overlap 4 0)
  | 42 => some (.overlap 4 0)
  | 43 => some (.overlap 4 0)
  | _ => none

def pairWitness38 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 4 5)
  | 29 => some (.overlap 6 3)
  | 30 => some (.overlap 5 6)
  | 31 => none
  | 32 => none
  | 33 => none
  | 34 => none
  | 35 => none
  | 36 => none
  | 37 => some (.mismatch 10 13)
  | 38 => none
  | 39 => some (.overlap 0 0)
  | 40 => some (.overlap 0 0)
  | 41 => some (.overlap 1 3)
  | 42 => some (.overlap 1 6)
  | 43 => some (.overlap 1 5)
  | _ => none

def pairWitness39 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 2 5)
  | 29 => some (.overlap 3 3)
  | 30 => some (.overlap 6 6)
  | 31 => some (.mismatch 10 4)
  | 32 => some (.mismatch 10 15)
  | 33 => some (.mismatch 10 6)
  | 34 => some (.mismatch 10 11)
  | 35 => some (.mismatch 10 20)
  | 36 => some (.mismatch 10 19)
  | 37 => none
  | 38 => some (.overlap 0 0)
  | 39 => none
  | 40 => some (.overlap 0 0)
  | 41 => some (.overlap 1 5)
  | 42 => some (.overlap 1 3)
  | 43 => some (.overlap 1 6)
  | _ => none

def pairWitness40 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 1 5)
  | 29 => some (.overlap 5 3)
  | 30 => some (.overlap 3 6)
  | 31 => some (.mismatch 10 5)
  | 32 => some (.mismatch 10 13)
  | 33 => some (.mismatch 10 7)
  | 34 => some (.mismatch 10 9)
  | 35 => some (.mismatch 10 22)
  | 36 => some (.mismatch 10 17)
  | 37 => some (.mismatch 10 15)
  | 38 => some (.overlap 0 0)
  | 39 => some (.overlap 0 0)
  | 40 => none
  | 41 => some (.overlap 1 6)
  | 42 => some (.overlap 1 5)
  | 43 => some (.overlap 1 3)
  | _ => none

def pairWitness41 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 6 5)
  | 29 => some (.overlap 4 3)
  | 30 => some (.overlap 2 6)
  | 31 => some (.overlap 0 1)
  | 32 => some (.overlap 0 4)
  | 33 => some (.overlap 0 2)
  | 34 => some (.overlap 0 3)
  | 35 => some (.overlap 0 6)
  | 36 => some (.overlap 0 5)
  | 37 => some (.overlap 0 4)
  | 38 => some (.overlap 1 3)
  | 39 => some (.overlap 1 5)
  | 40 => some (.overlap 1 6)
  | 41 => none
  | 42 => some (.overlap 0 0)
  | 43 => some (.overlap 0 0)
  | _ => none

def pairWitness42 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 5 5)
  | 29 => some (.overlap 1 3)
  | 30 => some (.overlap 4 6)
  | 31 => some (.overlap 0 1)
  | 32 => some (.overlap 0 4)
  | 33 => some (.overlap 0 2)
  | 34 => some (.overlap 0 3)
  | 35 => some (.overlap 0 6)
  | 36 => some (.overlap 0 5)
  | 37 => some (.overlap 0 4)
  | 38 => some (.overlap 1 6)
  | 39 => some (.overlap 1 3)
  | 40 => some (.overlap 1 5)
  | 41 => some (.overlap 0 0)
  | 42 => none
  | 43 => some (.overlap 0 0)
  | _ => none

def pairWitness43 (i : Fin 44) : Option RejectWitness := match i.val with
  | 0 => none
  | 1 => none
  | 2 => none
  | 3 => none
  | 4 => none
  | 5 => none
  | 6 => none
  | 7 => none
  | 8 => none
  | 9 => none
  | 10 => none
  | 11 => none
  | 12 => none
  | 13 => none
  | 14 => none
  | 15 => none
  | 16 => none
  | 17 => none
  | 18 => none
  | 19 => none
  | 20 => none
  | 21 => none
  | 22 => none
  | 23 => none
  | 24 => none
  | 25 => none
  | 26 => none
  | 27 => none
  | 28 => some (.overlap 3 5)
  | 29 => some (.overlap 2 3)
  | 30 => some (.overlap 1 6)
  | 31 => some (.overlap 0 1)
  | 32 => some (.overlap 0 4)
  | 33 => some (.overlap 0 2)
  | 34 => some (.overlap 0 3)
  | 35 => some (.overlap 0 6)
  | 36 => some (.overlap 0 5)
  | 37 => some (.overlap 0 4)
  | 38 => some (.overlap 1 5)
  | 39 => some (.overlap 1 6)
  | 40 => some (.overlap 1 3)
  | 41 => some (.overlap 0 0)
  | 42 => some (.overlap 0 0)
  | 43 => none
  | _ => none

def pairWitness (i : Fin 44) : ContactId → Option RejectWitness := match i.val with
  | 0 => pairWitness0
  | 1 => pairWitness1
  | 2 => pairWitness2
  | 3 => pairWitness3
  | 4 => pairWitness4
  | 5 => pairWitness5
  | 6 => pairWitness6
  | 7 => pairWitness7
  | 8 => pairWitness8
  | 9 => pairWitness9
  | 10 => pairWitness10
  | 11 => pairWitness11
  | 12 => pairWitness12
  | 13 => pairWitness13
  | 14 => pairWitness14
  | 15 => pairWitness15
  | 16 => pairWitness16
  | 17 => pairWitness17
  | 18 => pairWitness18
  | 19 => pairWitness19
  | 20 => pairWitness20
  | 21 => pairWitness21
  | 22 => pairWitness22
  | 23 => pairWitness23
  | 24 => pairWitness24
  | 25 => pairWitness25
  | 26 => pairWitness26
  | 27 => pairWitness27
  | 28 => pairWitness28
  | 29 => pairWitness29
  | 30 => pairWitness30
  | 31 => pairWitness31
  | 32 => pairWitness32
  | 33 => pairWitness33
  | 34 => pairWitness34
  | 35 => pairWitness35
  | 36 => pairWitness36
  | 37 => pairWitness37
  | 38 => pairWitness38
  | 39 => pairWitness39
  | 40 => pairWitness40
  | 41 => pairWitness41
  | 42 => pairWitness42
  | 43 => pairWitness43
  | _ => pairWitness0

def incompatible (i j : ContactId) : Bool := (pairWitness i j).isSome

def pairAllowed (i j : ContactId) : Bool := !(incompatible i j)

private theorem pair_checked_0 : ∀ j : ContactId,
    (pairWitness 0 j).all (fun w => rejectCheck (placed (contactMotion 0)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_1 : ∀ j : ContactId,
    (pairWitness 1 j).all (fun w => rejectCheck (placed (contactMotion 1)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_2 : ∀ j : ContactId,
    (pairWitness 2 j).all (fun w => rejectCheck (placed (contactMotion 2)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_3 : ∀ j : ContactId,
    (pairWitness 3 j).all (fun w => rejectCheck (placed (contactMotion 3)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_4 : ∀ j : ContactId,
    (pairWitness 4 j).all (fun w => rejectCheck (placed (contactMotion 4)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_5 : ∀ j : ContactId,
    (pairWitness 5 j).all (fun w => rejectCheck (placed (contactMotion 5)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_6 : ∀ j : ContactId,
    (pairWitness 6 j).all (fun w => rejectCheck (placed (contactMotion 6)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_7 : ∀ j : ContactId,
    (pairWitness 7 j).all (fun w => rejectCheck (placed (contactMotion 7)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_8 : ∀ j : ContactId,
    (pairWitness 8 j).all (fun w => rejectCheck (placed (contactMotion 8)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_9 : ∀ j : ContactId,
    (pairWitness 9 j).all (fun w => rejectCheck (placed (contactMotion 9)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_10 : ∀ j : ContactId,
    (pairWitness 10 j).all (fun w => rejectCheck (placed (contactMotion 10)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_11 : ∀ j : ContactId,
    (pairWitness 11 j).all (fun w => rejectCheck (placed (contactMotion 11)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_12 : ∀ j : ContactId,
    (pairWitness 12 j).all (fun w => rejectCheck (placed (contactMotion 12)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_13 : ∀ j : ContactId,
    (pairWitness 13 j).all (fun w => rejectCheck (placed (contactMotion 13)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_14 : ∀ j : ContactId,
    (pairWitness 14 j).all (fun w => rejectCheck (placed (contactMotion 14)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_15 : ∀ j : ContactId,
    (pairWitness 15 j).all (fun w => rejectCheck (placed (contactMotion 15)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_16 : ∀ j : ContactId,
    (pairWitness 16 j).all (fun w => rejectCheck (placed (contactMotion 16)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_17 : ∀ j : ContactId,
    (pairWitness 17 j).all (fun w => rejectCheck (placed (contactMotion 17)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_18 : ∀ j : ContactId,
    (pairWitness 18 j).all (fun w => rejectCheck (placed (contactMotion 18)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_19 : ∀ j : ContactId,
    (pairWitness 19 j).all (fun w => rejectCheck (placed (contactMotion 19)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_20 : ∀ j : ContactId,
    (pairWitness 20 j).all (fun w => rejectCheck (placed (contactMotion 20)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_21 : ∀ j : ContactId,
    (pairWitness 21 j).all (fun w => rejectCheck (placed (contactMotion 21)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_22 : ∀ j : ContactId,
    (pairWitness 22 j).all (fun w => rejectCheck (placed (contactMotion 22)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_23 : ∀ j : ContactId,
    (pairWitness 23 j).all (fun w => rejectCheck (placed (contactMotion 23)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_24 : ∀ j : ContactId,
    (pairWitness 24 j).all (fun w => rejectCheck (placed (contactMotion 24)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_25 : ∀ j : ContactId,
    (pairWitness 25 j).all (fun w => rejectCheck (placed (contactMotion 25)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_26 : ∀ j : ContactId,
    (pairWitness 26 j).all (fun w => rejectCheck (placed (contactMotion 26)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_27 : ∀ j : ContactId,
    (pairWitness 27 j).all (fun w => rejectCheck (placed (contactMotion 27)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_28 : ∀ j : ContactId,
    (pairWitness 28 j).all (fun w => rejectCheck (placed (contactMotion 28)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_29 : ∀ j : ContactId,
    (pairWitness 29 j).all (fun w => rejectCheck (placed (contactMotion 29)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_30 : ∀ j : ContactId,
    (pairWitness 30 j).all (fun w => rejectCheck (placed (contactMotion 30)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_31 : ∀ j : ContactId,
    (pairWitness 31 j).all (fun w => rejectCheck (placed (contactMotion 31)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_32 : ∀ j : ContactId,
    (pairWitness 32 j).all (fun w => rejectCheck (placed (contactMotion 32)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_33 : ∀ j : ContactId,
    (pairWitness 33 j).all (fun w => rejectCheck (placed (contactMotion 33)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_34 : ∀ j : ContactId,
    (pairWitness 34 j).all (fun w => rejectCheck (placed (contactMotion 34)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_35 : ∀ j : ContactId,
    (pairWitness 35 j).all (fun w => rejectCheck (placed (contactMotion 35)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_36 : ∀ j : ContactId,
    (pairWitness 36 j).all (fun w => rejectCheck (placed (contactMotion 36)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_37 : ∀ j : ContactId,
    (pairWitness 37 j).all (fun w => rejectCheck (placed (contactMotion 37)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_38 : ∀ j : ContactId,
    (pairWitness 38 j).all (fun w => rejectCheck (placed (contactMotion 38)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_39 : ∀ j : ContactId,
    (pairWitness 39 j).all (fun w => rejectCheck (placed (contactMotion 39)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_40 : ∀ j : ContactId,
    (pairWitness 40 j).all (fun w => rejectCheck (placed (contactMotion 40)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_41 : ∀ j : ContactId,
    (pairWitness 41 j).all (fun w => rejectCheck (placed (contactMotion 41)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_42 : ∀ j : ContactId,
    (pairWitness 42 j).all (fun w => rejectCheck (placed (contactMotion 42)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

private theorem pair_checked_43 : ∀ j : ContactId,
    (pairWitness 43 j).all (fun w => rejectCheck (placed (contactMotion 43)) (placed (contactMotion j)) zero w) = true := by
  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]
  decide +kernel

theorem pair_checked (i j : ContactId) :
    (pairWitness i j).all (fun w => rejectCheck (placed (contactMotion i)) (placed (contactMotion j)) zero w) = true := by
  revert j i
  exact (Fin.cases pair_checked_0 (Fin.cases pair_checked_1 (Fin.cases pair_checked_2 (Fin.cases pair_checked_3 (Fin.cases pair_checked_4 (Fin.cases pair_checked_5 (Fin.cases pair_checked_6 (Fin.cases pair_checked_7 (Fin.cases pair_checked_8 (Fin.cases pair_checked_9 (Fin.cases pair_checked_10 (Fin.cases pair_checked_11 (Fin.cases pair_checked_12 (Fin.cases pair_checked_13 (Fin.cases pair_checked_14 (Fin.cases pair_checked_15 (Fin.cases pair_checked_16 (Fin.cases pair_checked_17 (Fin.cases pair_checked_18 (Fin.cases pair_checked_19 (Fin.cases pair_checked_20 (Fin.cases pair_checked_21 (Fin.cases pair_checked_22 (Fin.cases pair_checked_23 (Fin.cases pair_checked_24 (Fin.cases pair_checked_25 (Fin.cases pair_checked_26 (Fin.cases pair_checked_27 (Fin.cases pair_checked_28 (Fin.cases pair_checked_29 (Fin.cases pair_checked_30 (Fin.cases pair_checked_31 (Fin.cases pair_checked_32 (Fin.cases pair_checked_33 (Fin.cases pair_checked_34 (Fin.cases pair_checked_35 (Fin.cases pair_checked_36 (Fin.cases pair_checked_37 (Fin.cases pair_checked_38 (Fin.cases pair_checked_39 (Fin.cases pair_checked_40 (Fin.cases pair_checked_41 (Fin.cases pair_checked_42 (Fin.cases pair_checked_43 (fun i => Fin.elim0 i)))))))))))))))))))))))))))))))))))))))))))))

theorem incompatible_checked (i j : ContactId) (h : incompatible i j = true) :
    ∃ w, rejectCheck (placed (contactMotion i)) (placed (contactMotion j)) zero w = true := by
  have checked := pair_checked i j
  unfold incompatible at h
  cases hw : pairWitness i j with
  | none => simp [hw] at h
  | some w => exact ⟨w, by simpa [hw] using checked⟩

theorem incompatible_self (i : ContactId) : incompatible i i = false := by
  revert i
  decide +kernel

private theorem accepted_checked : ∀ r : Fin 24,
    (fineAccepted r).all (fun t => (List.finRange 44).any (fun i =>
      decide ((contactMotion i).shift = t ∧ (contactMotion i).frame.mat = rotation r))) = true := by
  decide +kernel

theorem accepted_motion (r : Fin 24) (t : V3) (ht : t ∈ fineAccepted r) :
    ∃ i : ContactId, (contactMotion i).shift = t ∧
      (contactMotion i).frame.mat = rotation r := by
  have h := (List.all_eq_true.mp (accepted_checked r)) t ht
  obtain ⟨i, _, hi⟩ := List.any_eq_true.mp h
  exact ⟨i, of_decide_eq_true hi⟩

def excluded : List ContactId := [1, 3, 9, 10, 12, 13, 16, 17, 18, 19, 40, 41, 42, 43]

def surviving : List ContactId := [0, 2, 4, 5, 6, 7, 8, 11, 14, 15, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

def triggers : List ContactId := [5, 6, 7, 28, 29, 30]

def central : List ContactId := [4, 5, 6, 7, 28, 29, 30, 37]

def notch : List ContactId := [31, 32, 33, 34, 35, 36, 37]

def outer : List ContactId := [4, 5, 6, 7, 28, 29, 30]

def exclusionFace (i : Fin 44) : FaceId := match i.val with
  | 0 => 0
  | 1 => 0
  | 2 => 0
  | 3 => 0
  | 4 => 0
  | 5 => 0
  | 6 => 0
  | 7 => 0
  | 8 => 0
  | 9 => 4
  | 10 => 4
  | 11 => 0
  | 12 => 6
  | 13 => 6
  | 14 => 0
  | 15 => 0
  | 16 => 12
  | 17 => 12
  | 18 => 12
  | 19 => 12
  | 20 => 0
  | 21 => 0
  | 22 => 0
  | 23 => 0
  | 24 => 0
  | 25 => 0
  | 26 => 0
  | 27 => 0
  | 28 => 0
  | 29 => 0
  | 30 => 0
  | 31 => 0
  | 32 => 0
  | 33 => 0
  | 34 => 0
  | 35 => 0
  | 36 => 0
  | 37 => 0
  | 38 => 0
  | 39 => 0
  | 40 => 12
  | 41 => 12
  | 42 => 12
  | 43 => 12
  | _ => 0

def forcingTrace (i : Fin 44) : List (FaceId × ContactId) := match i.val with
  | 0 => []
  | 1 => []
  | 2 => []
  | 3 => []
  | 4 => []
  | 5 => [(0, 4), (2, 6), (3, 7), (12, 37), (13, 28), (14, 29), (18, 30)]
  | 6 => [(0, 4), (1, 5), (3, 7), (12, 37), (13, 28), (14, 29), (18, 30)]
  | 7 => [(0, 4), (1, 5), (2, 6), (12, 37), (13, 28), (14, 29), (18, 30)]
  | 8 => []
  | 9 => []
  | 10 => []
  | 11 => []
  | 12 => []
  | 13 => []
  | 14 => []
  | 15 => []
  | 16 => []
  | 17 => []
  | 18 => []
  | 19 => []
  | 20 => []
  | 21 => []
  | 22 => []
  | 23 => []
  | 24 => []
  | 25 => []
  | 26 => []
  | 27 => []
  | 28 => [(4, 4), (5, 5), (2, 6), (3, 7), (12, 37), (14, 29), (18, 30)]
  | 29 => [(4, 4), (5, 5), (2, 6), (3, 7), (12, 37), (13, 28), (18, 30)]
  | 30 => [(6, 4), (8, 6), (1, 5), (3, 7), (12, 37), (13, 28), (14, 29)]
  | 31 => []
  | 32 => []
  | 33 => []
  | 34 => []
  | 35 => []
  | 36 => []
  | 37 => []
  | 38 => []
  | 39 => []
  | 40 => []
  | 41 => []
  | 42 => []
  | 43 => []
  | _ => []

theorem exclusion_checked : ∀ i ∈ excluded,
    (faceOptions (exclusionFace i)).all (incompatible i) = true := by
  decide +kernel

def group : List GridMotion := GridMotion.identity :: outer.map contactMotion

theorem contactMotion_injective : ∀ i j : ContactId, contactMotion i = contactMotion j → i = j := by
  decide +kernel

theorem outer_inverse_notch : ∀ i ∈ outer,
    ∃ j ∈ notch, (contactMotion i).inv = contactMotion j := by
  decide +kernel

theorem ordinary_notch_inverse_trigger : ∀ i ∈ notch, i ≠ 37 →
    ∃ j ∈ triggers, (contactMotion i).inv = contactMotion j := by
  decide +kernel

theorem exceptional_relative :
    (contactMotion 37).inv.comp (contactMotion 39) = contactMotion 28 := by
  decide +kernel

theorem exceptional_sibling :
    (contactMotion 4).inv.comp (contactMotion 28) = contactMotion 39 := by
  decide +kernel

theorem same_notch_inverse : (contactMotion 37).inv = contactMotion 4 := by decide +kernel

theorem outer_inverse_notch_nonidentity : ∀ i ∈ outer, i ≠ 4 →
    ∃ j ∈ notch, j ≠ 37 ∧ (contactMotion i).inv = contactMotion j := by
  decide +kernel

theorem group_nodup : group.Nodup := by decide +kernel
theorem group_length : group.length = 8 := by decide +kernel

theorem group_matches_frozen : (group.map GridMotion.toPlacement).Perm Input.children := by
  decide +kernel

end Chair.GroupingData
