"""A face-motif proof of grouping, without searching complete stars.

Only A/B/C and face arrows enter the contact and implication calculations.
Raw caps validate the input description. The old certificate is read only
afterward to compare contacts and an optional independent star enumeration.
No project implementation is imported.
"""

from collections import Counter
from fractions import Fraction
from functools import cache
import hashlib
from itertools import combinations, permutations, product
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
ZERO = (0, 0, 0)
I = (1, 0, 0, 0, 1, 0, 0, 0, 1)
N = tuple(tuple(s if i == j else 0 for i in range(3)) for j in range(3) for s in (-1, 1))


def add(a, b): return tuple(x+y for x, y in zip(a, b))
def sub(a, b): return tuple(x-y for x, y in zip(a, b))
def scale(s, a): return tuple(s*x for x in a)
def act(r, p): return tuple(sum(r[3*i+j]*p[j] for j in range(3)) for i in range(3))
def tr(r): return tuple(r[3*j+i] for i in range(3) for j in range(3))
def mul(r, s): return tuple(sum(r[3*i+k]*s[3*k+j] for k in range(3)) for i in range(3) for j in range(3))
def cross(a, b): return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])


def determinant(r):
    a, b, c, d, e, f, g, h, i = r
    return a*(e*i-f*h)-b*(d*i-f*g)+c*(d*h-e*g)


def rotations():
    return sorted(r for order in permutations(range(3)) for signs in product((-1, 1), repeat=3)
                  if determinant(r := tuple(signs[i]*int(j == order[i]) for i in range(3) for j in range(3))) == 1)


def relative(a, b):
    t, r = a
    u, s = b
    return act(tr(r), sub(u, t)), mul(tr(r), s)


def matches(first, second, normal):
    name, arrow = first
    other, other_arrow = second
    if name == other == 'A':
        return other_arrow == cross(normal, arrow)
    return (name, other) in (('B', 'C'), ('C', 'B')) and other_arrow == scale(-1, arrow)


def validate_description(data, motifs, faces):
    """Reconstruct every frozen port from motif words and face arrows."""
    actual = set()
    for p in data['ports']:
        position = tuple(16*Fraction(x) for x in p['center'])
        actual.add((position, tuple(p['outward_normal']), p['signed_key'], tuple(p['u_axis']), tuple(p['v_axis'])))
    reconstructed = set()
    for (f, n), (name, u) in faces.items():
        v = cross(n, u)
        frame = tuple(x for row in zip(u, v, n) for x in row)
        for p, key, pu, pv in motifs['motifs'][name]['ports']:
            reconstructed.add((add(scale(8, f), act(frame, p)), n, key, act(frame, pu), act(frame, pv)))
    assert len(actual) == len(reconstructed) == 192 and actual == reconstructed
    # Check the three compact handshake rules against the actual motif ports.
    comparisons = 0
    for name, other in product('ABC', repeat=2):
        first = motifs['motifs'][name]['ports']
        second = motifs['motifs'][other]['ports']
        for r in rotations():
            if act(r, (0, 0, 1)) != (0, 0, -1):
                continue
            lhs = {(tuple(p), k, tuple(u), tuple(v)) for p, k, u, v in first}
            rhs = {(act(r, p), -k, act(r, u), act(r, v)) for p, k, u, v in second}
            assert (lhs == rhs) == matches((name, (1, 0, 0)), (other, act(r, (1, 0, 0))), (0, 0, 1))
            comparisons += 1
    return comparisons


def write_tables(certificate, report):
    """Readable, mechanically generated appendix to the short proof."""
    def vector(v):
        return '('+','.join(map(str, v))+')'

    def arrow(v):
        return next(('+' if x > 0 else '-')+'xyz'[i] for i, x in enumerate(v) if x)

    def rotation(r):
        return '('+','.join(next(('' if x > 0 else '-')+'xyz'[j] for j, x in enumerate(r[3*i:3*i+3]) if x)
                            for i in range(3))+')'

    rows = ['# Face-motif grouping: generated proof tables', '',
            'Generated by `uv run --locked python strong/audit/motif_grouping.py`.', '',
            'Read the [short proof](../MOTIF_GROUPING.md) first. Numbers below are',
            'stable indices in sorted face/contact lists, not additional matching rules.', '',
            '## Face layout', '',
            'Face centers are doubled integers. Each arrow is the canonical motif U axis.', '',
            '| Face | Twice center | Normal | Motif | Arrow |', '|---:|---|---|---|---|']
    for f in certificate['face_table']:
        rows.append(f"| {f['id']} | {vector(f['center_times_2'])} | {arrow(f['normal'])} | {f['motif']} | {arrow(f['arrow'])} |")
    rows += ['', '## All locally fitting contacts', '',
             'A neighbor is placed by `x ↦ center + R(x)`. `D` denotes a diagonal',
             'contact used in the group; `N` is the identically oriented notch',
             'occupant. The six mixed-sign `D` contacts are the central triggers.', '',
             '| Contact | Name | Center | R(x,y,z) | Covered face indices |', '|---:|---|---|---|---|']
    names = {}
    for c in certificate['contact_table']:
        i, t = c['id'], c['center']
        name = ''
        if all(abs(x) == 1 for x in t) and tuple(t) != (1, 1, 1):
            name = 'D'+''.join('+' if x > 0 else '-' for x in t)
        elif tuple(t) == (1, 1, 1) and tuple(c['rotation']) == I:
            name = 'N'
        names[i] = name or str(i)
        rows.append(f"| {i} | {name} | {vector(t)} | {rotation(c['rotation'])} | {', '.join(map(str, c['faces']))} |")
    rows += ['', '## Fourteen contacts that cannot occur in a tiling', '',
             'Each row names an anchor face left impossible to cover. Every listed',
             'alternative overlaps the assumed neighbor or violates one of the three',
             'face handshakes with it. The JSON certificate gives an explicit cube or',
             'face witness for each incompatibility. All rows use the initial 44 contacts.', '',
             '| Assumed contact | Unfillable face | All candidates for that face |', '|---:|---:|---|']
    for batch in certificate['pruning']:
        for w in batch:
            blocked = ', '.join(f"{x['candidate']} ({'overlap' if 'overlap_cube' in x['reason'] else 'motif mismatch'})"
                                for x in w['blocked_alternatives'])
            rows.append(f"| {w['candidate']} | {w['unfillable_face']} | {blocked} |")
    rows += ['', '## Six forced central neighborhoods', '',
             'Starting with the named contact, repeatedly cover the indicated face.',
             'Exactly one of the remaining 30 contacts is compatible with the contacts',
             'already selected. Entries are `face → forced contact`, in order.', '',
             '| Initial contact | Forced steps |', '|---|---|']
    for i, w in certificate['trigger_propagation'].items():
        steps = '; '.join(f"{s['face']} → {names[s['forced_candidate']]}" for s in w['steps'])
        rows.append(f'| {names[i]} | {steps} |')
    rows += ['', '## Notch cases', '',
             '| Notch contact | Anchor seen from that neighbor | Neighborhoods in cross-check |', '|---|---|---:|']
    for i in report['notch_options']:
        other = report['ordinary_notch_reciprocals'].get(i)
        rows.append(f"| {names[i]} | {names[other] if other is not None else 'D---; use the extra axial neighbor'} | {report['star_parent_counts'][str(i)]} |")
    rows += ['', 'The single central neighborhood accounts for the remaining star.', '',
             '## Exceptional identical-notch case', '',
             'Assume N is present and none of the six triggers is present.',
             'The local propagation forces contacts 21, 25, and 39. Contact 39 alone',
             'is enough: from N it is D+-- and therefore forces N to be a group center.', '',
             '## Uniqueness', '',
             'For six outer children the center has a nonidentity notch orientation,',
             'which excludes the central neighborhood. For D---, the sibling D+--',
             'appears as contact 39 and also excludes the central neighborhood.',
             'Thus all seven outer children select the same center by the local parent rule.', '']
    (HERE / 'motif_grouping_tables.md').write_text('\n'.join(rows))


def run():
    raw = (HERE / 'frozen_v1/candidate.json').read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    data = json.loads(raw)
    motifs = json.loads((HERE / 'face_motifs.json').read_text())
    assert digest == motifs['candidate_sha256'] == json.loads((HERE / 'frozen_v1/manifest.json').read_text())['candidate_sha256']
    base = frozenset(map(tuple, data['coarse_cubes']))
    faces = {(tuple(f['center_times_2']), tuple(f['normal'])): (f['motif'], tuple(f['arrow']))
             for f in motifs['face_descriptors']}
    face_order = sorted(faces)
    ids = {f: i for i, f in enumerate(face_order)}
    bridge_checks = validate_description(data, motifs, faces)
    anchor = ZERO, I

    @cache
    def placed(p):
        t, r = p
        cubes = frozenset(add(tuple((x-1)//2 for x in act(r, add(scale(2, q), (1, 1, 1)))), t) for q in base)
        moved = {(add(act(r, f), scale(2, t)), act(r, n)): (name, act(r, u)) for (f, n), (name, u) in faces.items()}
        return cubes, moved

    @cache
    def conflict(a, b):
        ac, af = placed(a)
        bc, bf = placed(b)
        if common := ac & bc:
            return {'overlap_cube': min(common)}
        for (f, n), value in sorted(af.items()):
            other = bf.get((f, scale(-1, n)))
            if other is not None and not matches(value, other, n):
                return {'mismatched_face': (f, n), 'first': value, 'second': other}
        return None

    catalogue = {}
    for r in rotations():
        cubes, _ = placed((ZERO, r))
        offsets = {sub(add(q, n), b) for q in base for n in N if add(q, n) not in base for b in cubes}
        for t in sorted(offsets):
            p = t, r
            other_cubes, other_faces = placed(p)
            if base & other_cubes:
                continue
            cover = frozenset(ids[f, n] for f, n in faces if (f, scale(-1, n)) in other_faces)
            if cover:
                catalogue[p] = cover, conflict(anchor, p) is None
    candidates = sorted(p for p, (_, legal) in catalogue.items() if legal)
    index = {p: i for i, p in enumerate(candidates)}
    cover = [catalogue[p][0] for p in candidates]
    bad = [{j for j in range(len(candidates)) if i == j or cover[i] & cover[j] or conflict(candidates[i], candidates[j])}
           for i in range(len(candidates))]
    all_faces = set(range(24))

    # A candidate cannot occur if one remaining anchor face has no neighbor
    # compatible with it. All removals in a round use the preceding domain.
    domain, pruning = set(range(len(candidates))), []
    while True:
        removed = []
        for i in sorted(domain):
            blocked_face = next((f for f in sorted(all_faces-cover[i])
                                 if not any(f in cover[j] for j in domain-bad[i])), None)
            if blocked_face is not None:
                alternatives = [j for j in sorted(domain) if blocked_face in cover[j]]
                removed.append({'candidate': i, 'unfillable_face': blocked_face,
                                'blocked_alternatives': [{'candidate': j, 'reason': conflict(candidates[i], candidates[j])}
                                                         for j in alternatives]})
                assert all(conflict(candidates[i], candidates[j]) for j in alternatives)
        if not removed:
            break
        pruning.append(removed)
        domain -= {w['candidate'] for w in removed}

    def force(seed, excluded=()):
        chosen = set(seed)
        steps = []
        while True:
            assert not any(j in bad[i] for i, j in combinations(chosen, 2))
            filled = set().union(*(cover[i] for i in chosen))
            available = domain-set(excluded)-set().union(*(bad[i] for i in chosen))
            options = {f: sorted(i for i in available if f in cover[i]) for f in sorted(all_faces-filled)}
            assert all(options.values())
            single = next(((f, opts[0]) for f, opts in options.items() if len(opts) == 1), None)
            if single is None:
                return chosen, steps, available, filled
            f, i = single
            steps.append({'face': f, 'forced_candidate': i})
            chosen.add(i)

    triggers = {i for i, (t, _) in enumerate(candidates)
                if all(abs(x) == 1 for x in t) and t not in ((1, 1, 1), (-1, -1, -1))}
    assert len(triggers) == 6
    forcing = {}
    for i in sorted(triggers):
        selected, steps, _, filled = force([i])
        assert filled == all_faces
        forcing[i] = {'neighborhood': sorted(selected), 'steps': steps}
    assert len({tuple(w['neighborhood']) for w in forcing.values()}) == 1
    central = set(next(iter(forcing.values()))['neighborhood'])
    notch_faces = {i for i, (f, _) in enumerate(face_order) if sorted(f) == [0, 1, 1]}
    notch_options = {i for i in domain if cover[i] & notch_faces}
    assert len(notch_options) == 7
    assert all(cover[i] == notch_faces and candidates[i][0] == (1, 1, 1) for i in notch_options)
    identical_notch = index[((1, 1, 1), I)]
    ordinary_notch = notch_options-{identical_notch}
    reciprocal = {i: index[relative(candidates[i], anchor)] for i in ordinary_notch}
    assert set(reciprocal.values()) == triggers

    # If none of the six triggers occurs, the identical notch case forces
    # a +x axial neighbor. Seen by the notch occupant, it is a trigger.
    selected, special_steps, _, _ = force([identical_notch], excluded=triggers)
    axial = next(i for i in selected if candidates[i][0] == (2, 0, 0))
    seen_by_notch = index[relative(candidates[identical_notch], candidates[axial])]
    assert seen_by_notch in triggers
    # The proof can inspect just this one face, without the other two
    # singleton steps produced by the generic propagation routine.
    axial_face = ids[((2, -1, -1), (1, 0, 0))]
    axial_options = {i for i in domain-triggers-bad[identical_notch] if axial_face in cover[i]}
    assert axial_options == {axial}
    exceptional = {'notch_candidate': identical_notch, 'excluded_triggers': sorted(triggers),
                   'forced_candidates': sorted(selected), 'steps': special_steps,
                   'axial_witness': axial, 'witness_seen_from_notch': seen_by_notch,
                   'single_face': axial_face,
                   'face_options_after_pruning': sorted(i for i in domain if axial_face in cover[i]),
                   'blocked_by_notch': [{'candidate': i, 'reason': conflict(candidates[identical_notch], candidates[i])}
                                        for i in sorted(domain-triggers) if axial_face in cover[i] and i != axial]}

    # Derive the group from the central neighborhood; compare to the old
    # substitution only after it has been recovered this way.
    outer = central-{identical_notch}
    group = [anchor, *(candidates[i] for i in sorted(outer))]
    expected = {(tuple(c['center']), tuple(x for row in c['matrix'] for x in row)) for c in data['children']}
    assert set(group) == expected and len(group) == 8
    group_cells = set().union(*(placed(p)[0] for p in group))
    assert len(group_cells) == 56
    assert group_cells == {add(scale(2, q), b) for q in base for b in product((0, 1), repeat=3)}
    assert all(conflict(a, b) is None for a, b in combinations(group, 2))

    # Intrinsic parent map: a trigger means self; otherwise the notch owner.
    # Show each of the seven outer children selects this group's center.
    ownership = []
    for child in group[1:]:
        parent = relative(child, anchor)
        pi = index[parent]
        assert pi in notch_options
        if pi in ordinary_notch:
            # A central neighborhood has the identical notch occupant only.
            assert pi not in central
            ownership.append({'child': child, 'notch_parent': pi, 'noncentral_reason': 'nonidentity notch orientation'})
        else:
            sibling = next(s for s in group if s != child and relative(child, s) == candidates[axial])
            assert axial not in central
            ownership.append({'child': child, 'notch_parent': pi, 'noncentral_reason': 'axial sibling excludes central neighborhood',
                              'sibling': sibling, 'sibling_contact': axial})

    # Comparison only: regenerate all complete stars by first-uncovered-face
    # exact cover, independently of the old star search implementation.
    stars = []
    def enumerate_stars(remaining, eligible, chosen):
        if not remaining:
            stars.append(tuple(sorted(chosen)))
            return
        f = min(remaining)
        for i in sorted(eligible):
            if f in cover[i]:
                enumerate_stars(remaining-cover[i], eligible-bad[i], (*chosen, i))
    enumerate_stars(all_faces, set(range(len(candidates))), ())
    old = json.loads((HERE / 'coordinate_certificate.json').read_text())
    assert old['candidate_sha256'] == digest
    assert candidates == [(tuple(t), tuple(r)) for t, r in old['neighbor_candidates']]
    assert {candidates[i] for i in domain} == {(tuple(t), tuple(r)) for t, r in old['closed_substitution_contacts']}
    assert sorted(stars) == sorted(map(tuple, old['stars']))
    assert len(stars) == len(set(stars)) == 33
    assert [s for s in stars if set(s) & triggers] == [tuple(sorted(central))]
    role_counts = Counter()
    for star in stars:
        s = set(star)
        role_counts['center' if s & triggers else str(next(iter(s & notch_options)))] += 1

    report = {'status': 'passed', 'candidate_sha256': digest,
              'scope': 'Finite grid grouping proof in A/B/C motif language. Analytic grid enforcement and macro recurrence remain separate.',
              'implementation': 'No project imports; motif-only contacts and propagation. Cap reconstruction and previous certificate are comparison checks.',
              'ports_reconstructed': 192, 'canonical_motif_handshakes_checked': bridge_checks,
              'geometric_contacts': len(catalogue), 'legal_contacts': len(candidates),
              'pruning_rounds': len(pruning), 'unextendible_contacts_removed': sum(map(len, pruning)),
              'remaining_contacts': len(domain), 'central_trigger_contacts': sorted(triggers),
              'remaining_contacts_equal_substitution_closure': True,
              'central_neighborhood': sorted(central), 'notch_options': sorted(notch_options),
              'ordinary_notch_reciprocals': reciprocal, 'exceptional_case': exceptional,
              'group_size': len(group), 'outer_children_select_same_parent': len(ownership),
              'derived_group_coarse_union_is_double_chair': True,
              'complete_stars_crosschecked': len(stars), 'star_parent_counts': dict(role_counts),
              'grouping_proof_uses_complete_star_enumeration': False}
    certificate = {'candidate_sha256': digest,
                   'face_table': [{'id': i, 'center_times_2': f, 'normal': n, 'motif': faces[f, n][0], 'arrow': faces[f, n][1]}
                                  for i, (f, n) in enumerate(face_order)],
                   'contact_table': [{'id': i, 'center': t, 'rotation': r, 'faces': sorted(cover[i])} for i, (t, r) in enumerate(candidates)],
                   'pruning': pruning, 'trigger_propagation': forcing, 'exceptional_case': exceptional,
                   'derived_group': group, 'parent_ownership': ownership, 'crosschecked_stars': sorted(stars)}
    (HERE / 'motif_grouping_verification.json').write_text(json.dumps(report, indent=2)+'\n')
    (HERE / 'motif_grouping_certificate.json').write_text(json.dumps(certificate, indent=2)+'\n')
    write_tables(certificate, report)
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    run()
