"""Rebuild the finite hierarchy proof from frozen coordinates alone.

Standard library only. No imports from the search, old checkers, NumPy,
SymPy, or an SAT solver. Rotations are generated by quarter turns; cubes
are transformed by their eight corners; contacts use explicit face patches.

This is a separate implementation by the same assistant, not an external
mathematical review. The only construction input is frozen_v1/candidate.json.
"""

from dataclasses import dataclass
from fractions import Fraction
import hashlib
from itertools import combinations, product
import json
from pathlib import Path
import time


HERE = Path(__file__).resolve().parent
I = (1, 0, 0, 0, 1, 0, 0, 0, 1)
ZERO = (0, 0, 0)
AXES = ((1, 0, 0), (0, 1, 0), (0, 0, 1))
NORMALS = tuple(tuple(sign*x for x in axis) for axis in AXES for sign in (-1, 1))
CORNERS = tuple(product((0, 1), repeat=3))


def add(a, b):
    return tuple(x+y for x, y in zip(a, b))


def sub(a, b):
    return tuple(x-y for x, y in zip(a, b))


def scale(n, p):
    return tuple(n*x for x in p)


def apply(m, p):
    return tuple(sum(m[3*j+k]*p[k] for k in range(3)) for j in range(3))


def multiply(a, b):
    return tuple(sum(a[3*j+k]*b[3*k+l] for k in range(3))
                 for j in range(3) for l in range(3))


def transpose(m):
    return tuple(m[3*j+k] for k in range(3) for j in range(3))


def determinant(m):
    a, b, c, d, e, f, g, h, i = m
    return a*(e*i-f*h)-b*(d*i-f*g)+c*(d*h-e*g)


def rotation_group():
    rx = (1, 0, 0, 0, 0, -1, 0, 1, 0)
    ry = (0, 0, 1, 0, 1, 0, -1, 0, 0)
    found, queue = {I}, [I]
    for m in queue:
        for generator in (rx, ry):
            n = multiply(generator, m)
            if n not in found:
                found.add(n)
                queue.append(n)
    assert len(found) == 24
    for m in found:
        assert determinant(m) == 1 and multiply(m, transpose(m)) == I
        assert all(multiply(m, n) in found for n in found)
    return sorted(found)


def transform_cube(cube, matrix):
    corners = [apply(matrix, add(cube, q)) for q in CORNERS]
    lower = tuple(min(p[k] for p in corners) for k in range(3))
    assert {sub(p, lower) for p in corners} == set(CORNERS)
    return lower


def exposed_faces(cubes):
    # Face centers use half-unit coordinates, represented by doubled integers.
    return {(add(add(scale(2, q), (1, 1, 1)), n), n)
            for q in cubes for n in NORMALS if add(q, n) not in cubes}


@dataclass
class Solid:
    cubes: frozenset
    # (doubled face center, outward normal) ->
    # {port center in sixteenths: (signed key, ordered u axis, ordered v axis)}
    faces: dict


def from_data(data, keys=None):
    cubes = frozenset(tuple(p) for p in data["coarse_cubes"])
    faces = {f: {} for f in exposed_faces(cubes)}
    width = Fraction(data["half_width"])
    depth = Fraction(data["height_unit"])
    assert width > 0 and depth > 0
    for i, port in enumerate(data["ports"]):
        p = tuple(Fraction(x) for x in port["center"])
        n, u, v = (tuple(port[k]) for k in ("outward_normal", "u_axis", "v_axis"))
        assert n in NORMALS and u in NORMALS and v in NORMALS
        assert sum(a*b for a, b in zip(u, v)) == 0
        assert sum(a*b for a, b in zip(u, n)) == sum(a*b for a, b in zip(v, n)) == 0
        possible = []
        for f, fn in faces:
            if fn != n:
                continue
            center = tuple(Fraction(x, 2) for x in f)
            delta = sub(p, center)
            if all(delta[k] == 0 if n[k] else abs(delta[k])+width < Fraction(1, 2)
                   for k in range(3)):
                possible.append((f, fn))
        assert len(possible) == 1
        face = possible[0]
        assert sub(p, tuple(Fraction(x, 2) for x in face[0])) == tuple(Fraction(3*a+b, 16) for a, b in zip(u, v))
        p16 = scale(16, p)
        assert all(x.denominator == 1 for x in p16)
        p16 = tuple(int(x) for x in p16)
        assert p16 not in faces[face]
        key = port["signed_key"] if keys is None else keys[i]
        faces[face][p16] = (key, u, v)
    assert all(len(features) == 8 for features in faces.values())
    assert len(cubes) == 7 and len(faces) == 24
    assert sum(k for face in faces.values() for k, _, _ in face.values()) == 0
    return Solid(cubes, faces)


def rotate_solid(solid, matrix):
    cubes = frozenset(transform_cube(q, matrix) for q in solid.cubes)
    faces = {(apply(matrix, f), apply(matrix, n)):
             {apply(matrix, p): (key, apply(matrix, u), apply(matrix, v))
              for p, (key, u, v) in features.items()}
             for (f, n), features in solid.faces.items()}
    assert set(faces) == exposed_faces(cubes)
    return Solid(cubes, faces)


def face_fit(a, b, shift):
    delta = scale(16, shift)
    moved = {add(p, delta): (-key, u, v) for p, (key, u, v) in b.items()}
    return a == moved


def contact(a, b, shift, face_ids):
    if any(add(q, shift) in a.cubes for q in b.cubes):
        return None  # Interior overlap of coarse unit cubes.
    mask, fits = 0, True
    for (f, n), features in b.faces.items():
        opposite = (add(f, scale(2, shift)), scale(-1, n))
        if opposite in a.faces:
            mask |= 1 << face_ids[opposite]
            fits &= face_fit(a.faces[opposite], features, shift)
    return mask, fits


def contact_catalogue(solid, rotations):
    ids = {f: i for i, f in enumerate(sorted(solid.faces))}
    oriented = {m: rotate_solid(solid, m) for m in rotations}
    result = {}
    for matrix, other in oriented.items():
        ranges = [range(min(q[k] for q in solid.cubes)-max(q[k]+1 for q in other.cubes),
                        max(q[k]+1 for q in solid.cubes)-min(q[k] for q in other.cubes)+1)
                  for k in range(3)]
        for t in product(*ranges):
            value = contact(solid, other, t, ids)
            if value is not None and value[0]:
                result[t, matrix] = value
    return result, oriented


def relative(a, b):
    ca, ra = a
    cb, rb = b
    inverse = transpose(ra)
    return apply(inverse, sub(cb, ca)), multiply(inverse, rb)


def move_placement(placement, center, matrix):
    c, r = placement
    return add(center, apply(matrix, c)), multiply(matrix, r)


def placed_cells(placement, oriented):
    c, r = placement
    return frozenset(add(q, c) for q in oriented[r].cubes)


def incompatible(a, b, oriented, catalogue):
    if placed_cells(a, oriented) & placed_cells(b, oriented):
        return True
    relation = catalogue.get(relative(a, b))
    return relation is not None and not relation[1]


def assemble(children, solid, oriented):
    cubes, patches = set(), {}
    for center, matrix in children:
        other = oriented[matrix]
        cells = {add(center, q) for q in other.cubes}
        assert not cubes & cells
        cubes.update(cells)
        for (f, n), features in other.faces.items():
            face = add(f, scale(2, center)), n
            moved = {add(p, scale(16, center)): value for p, value in features.items()}
            opposite = face[0], scale(-1, n)
            if opposite in patches:
                assert face_fit(patches.pop(opposite), moved, ZERO)
            else:
                assert face not in patches
                patches[face] = moved
    expected = {add(scale(2, q), bit) for q in solid.cubes for bit in CORNERS}
    assert cubes == expected
    assert set(patches) == exposed_faces(cubes)
    return Solid(frozenset(cubes), patches)


def close_language(children, catalogue):
    found = {relative(a, b) for a, b in product(children, repeat=2)
             if a != b and relative(a, b) in catalogue}
    queue = list(sorted(found))
    for t, r in queue:
        other_children = [move_placement(child, scale(2, t), r) for child in children]
        for a, b in product(children, other_children):
            relation = relative(a, b)
            if relation in catalogue and relation not in found:
                found.add(relation)
                queue.append(relation)
    assert all(catalogue[p][1] for p in found)
    return found


def all_stars(catalogue, oriented):
    candidates = sorted(p for p, (_, fits) in catalogue.items() if fits)
    covers = [catalogue[p][0] for p in candidates]
    conflicts = [1 << i for i in range(len(candidates))]
    for i, j in combinations(range(len(candidates)), 2):
        if covers[i] & covers[j] or incompatible(candidates[i], candidates[j], oriented, catalogue):
            conflicts[i] |= 1 << j
            conflicts[j] |= 1 << i
    by_face = [sum(1 << i for i, mask in enumerate(covers) if mask & (1 << face)) for face in range(24)]
    stars, nodes = [], []

    def enumerate_covers(remaining_faces, available, selected):
        node_id = len(nodes)
        record = {"remaining_faces": remaining_faces, "available_neighbors": available}
        nodes.append(record)
        if not remaining_faces:
            record["complete"] = sorted(selected)
            stars.append(tuple(sorted(selected)))
            return node_id
        face = min((f for f in range(24) if remaining_faces & (1 << f)),
                   key=lambda f: (by_face[f] & available).bit_count())
        options = by_face[face] & available
        record["face"] = face
        record["branches"] = []
        for i in range(len(candidates)):
            if options & (1 << i):
                child = enumerate_covers(remaining_faces & ~covers[i], available & ~conflicts[i], (*selected, i))
                record["branches"].append([i, child])
        return node_id

    enumerate_covers((1 << 24)-1, (1 << len(candidates))-1, ())
    assert len(stars) == len(set(stars))
    for star in stars:
        covered = 0
        for i in star:
            assert not covered & covers[i]
            covered |= covers[i]
        assert covered == (1 << 24)-1
        assert all(not incompatible(candidates[i], candidates[j], oriented, catalogue) for i, j in combinations(star, 2))
    return candidates, sorted(stars), nodes


def grouping(children, candidates, stars, oriented, catalogue):
    anchor = ZERO, I
    groups = [frozenset(relative(role, child) for child in children) for role in children]
    assert all(anchor in group and len(group) == 8 for group in groups)
    neighborhoods = [frozenset([anchor, *(candidates[i] for i in star)]) for star in stars]
    central = [groups[0] <= s for s in neighborhoods]
    witnesses = []
    for s, neighborhood in enumerate(neighborhoods):
        if central[s]:
            witnesses.append({"star": s, "role": "central"})
            continue
        for neighbor in sorted(neighborhood - {anchor}):
            must_appear = {relative(neighbor, p) for p in neighborhood if p != neighbor
                           and relative(neighbor, p) in catalogue}
            possibilities = [j for j, other in enumerate(neighborhoods) if must_appear <= other]
            if (possibilities and relative(neighbor, anchor) in groups[0]
                    and all(central[j] for j in possibilities)):
                witnesses.append({"star": s, "role": "outer", "forced_parent": neighbor,
                                  "parent_star_options": possibilities,
                                  "required_parent_neighbors": sorted(must_appear)})
                break
        else:
            raise AssertionError(("Uncertified star", s, sorted(neighborhood)))
    overlaps = []
    for i, j in combinations(range(8), 2):
        obstruction = next(((a, b) for a, b in combinations(sorted(groups[i] | groups[j]), 2)
                            if incompatible(a, b, oriented, catalogue)), None)
        assert obstruction is not None, ("Two groups can coexist", i, j)
        overlaps.append({"roles": [i, j], "conflicting_tiles": obstruction})
    return {"central_stars": sum(central), "forcing_witnesses": witnesses,
            "overlap_obstructions": overlaps}


def controls(data, solid, rotations, catalogue, closed):
    flat = from_data(data, [0]*len(data["ports"]))
    flat_catalogue, _ = contact_catalogue(flat, rotations)
    residues = {(q[0]+2*q[1]+4*q[2]) % 7 for q in flat.cubes}
    assert residues == set(range(7))
    periodic_contacts = [p for p in flat_catalogue if p[1] == I and
                         (p[0][0]+2*p[0][1]+4*p[0][2]) % 7 == 0]
    assert periodic_contacts and all(flat_catalogue[p][1] for p in periodic_contacts)
    keys = [p["signed_key"] for p in data["ports"]]
    a, b = next((a, b) for a, b in combinations(range(len(keys)), 2) if 0 < keys[a] != keys[b] > 0)
    keys[a], keys[b] = keys[b], keys[a]
    damaged = from_data(data, keys)
    damaged_orientations = {m: rotate_solid(damaged, m) for m in rotations}
    ids = {f: i for i, f in enumerate(sorted(damaged.faces))}
    broken = [p for p in sorted(closed) if not contact(damaged, damaged_orientations[p[1]], p[0], ids)[1]]
    assert broken
    return {"unmarked_periodic_control": {"quotient_voxels": 7, "residues": sorted(residues),
                                         "matching_lattice_contacts": len(periodic_contacts),
                                         "all_geometric_contacts_allowed": all(v[1] for v in flat_catalogue.values())},
            "damaged_key_control": {"swapped_ports": [a, b], "volume_preserved": sum(keys) == 0,
                                    "broken_required_contact_count": len(broken), "first_broken_contact": broken[0],
                                    "scope": "Rejects the original substitution certificate for this mutation; not a non-tilability claim."}}


def run():
    started = time.monotonic()
    raw = (HERE / "frozen_v1/candidate.json").read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    manifest = json.loads((HERE / "frozen_v1/manifest.json").read_text())
    assert digest == manifest["candidate_sha256"]
    data = json.loads(raw)
    rotations = rotation_group()
    solid = from_data(data)
    children = [(tuple(c["center"]), tuple(x for row in c["matrix"] for x in row)) for c in data["children"]]
    assert children[0] == (ZERO, I) and all(r in rotations for _, r in children)
    catalogue, oriented = contact_catalogue(solid, rotations)
    coarse_symmetries = [m for m in rotations if oriented[m].cubes == solid.cubes]
    keyed_symmetries = [m for m in coarse_symmetries if oriented[m].faces == solid.faces]
    assert keyed_symmetries == [I]
    allowed = {p for p, value in catalogue.items() if value[1]}
    print(f"Coordinates only: {len(catalogue)} geometric contacts; {len(allowed)} legal contacts", flush=True)
    macro = assemble(children, solid, oriented)
    closed = close_language(children, catalogue)
    candidates, stars, tree = all_stars(catalogue, oriented)
    print(f"Closed substitution contacts: {len(closed)}; complete stars: {len(stars)}", flush=True)
    group = grouping(children, candidates, stars, oriented, catalogue)
    macro_catalogue, _ = contact_catalogue(macro, rotations)
    macro_allowed = {p for p, value in macro_catalogue.items() if value[1]}
    assert all(all(v % 2 == 0 for v in c) for c, _ in macro_allowed)
    assert {(tuple(v//2 for v in c), r) for c, r in macro_allowed} == allowed
    print(f"Macro contacts: {len(macro_catalogue)}; legal: {len(macro_allowed)}; exact deflation passed", flush=True)
    control = controls(data, solid, rotations, catalogue, closed)
    result = {"status": "passed", "candidate_sha256": digest,
              "implementation": "Python standard library; no original geometry imports or solver dependencies",
              "independence_limit": "Separate implementation by the same assistant; not external review",
              "rotations": len(rotations), "coarse_proper_symmetries": len(coarse_symmetries),
              "keyed_proper_symmetries": len(keyed_symmetries),
              "geometric_contacts": len(catalogue), "legal_contacts": len(allowed),
              "closed_substitution_contacts": len(closed), "complete_stars": len(stars),
              "star_search_nodes": len(tree), "certified_stars": len(group["forcing_witnesses"]),
              "central_stars": group["central_stars"], "incompatible_group_pairs": len(group["overlap_obstructions"]),
              "macro_geometric_contacts": len(macro_catalogue), "macro_legal_contacts": len(macro_allowed),
              "deflation_preserves_grid_and_rules": True, "controls": control,
              "elapsed_seconds": time.monotonic()-started,
              "scope": "Finite lemmas for existence and unique recursive grouping in the integer-grid model"}
    certificate = {"candidate_sha256": digest, "legal_contacts": sorted(allowed),
                   "closed_substitution_contacts": sorted(closed), "neighbor_candidates": candidates,
                   "stars": stars, "exhaustive_star_search_tree": tree, **group,
                   "legal_macro_contacts": sorted(macro_allowed)}
    (HERE / "coordinate_certificate.json").write_text(json.dumps(certificate, indent=2)+"\n")
    (HERE / "coordinate_verification.json").write_text(json.dumps(result, indent=2)+"\n")
    print(json.dumps(result, indent=2), flush=True)


if __name__ == "__main__":
    run()
