"""Export exact frozen construction literals, not assumed geometric theorems.

Run from the repository root with uv. --check detects any stale Lean input.
The Lean development reconstructs the exposed faces and eight-child boundary.
"""

import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "strong/audit/frozen_v1/candidate.json"
SHA256 = "95284fd672945936a383b046f67f5d4b11ab34d05909d0548f4ac95a565b3e54"


def vec(values):
    return "⟨" + ", ".join(str(v) for v in values) + "⟩"


def mat(rows):
    return vec(vec(row) for row in rows)


def render():
    raw = SOURCE.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SHA256
    data = json.loads(raw)
    cells = ",\n  ".join(vec(q) for q in data["coarse_cubes"])
    ports = []
    for port in data["ports"]:
        p16 = [16 * Fraction(v) for v in port["center"]]
        assert all(v.denominator == 1 for v in p16)
        ports.append("⟨" + ", ".join([
            vec(int(v) for v in p16), str(port["signed_key"]),
            vec(port["u_axis"]), vec(port["v_axis"]),
            vec(port["outward_normal"]),
        ]) + "⟩")
    children = ",\n  ".join(
        f"⟨{vec(child['center'])}, {mat(child['matrix'])}⟩"
        for child in data["children"]
    )
    port_text = ",\n  ".join(ports)
    return f'''-- Generated by uv run --locked python formal/generate_input.py.
-- Frozen candidate SHA-256: {SHA256}
-- Only original cells, ports, and children are exported. Do not edit.
import Chair.Geometry

namespace Chair.Input

def cells : List V3 := [
  {cells}]

def ports : List RawPort := [
  {port_text}]

def children : List Placement := [
  {children}]

end Chair.Input
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = HERE / "Chair/Input.lean"
    expected = render()
    if args.check:
        assert target.read_text() == expected, "Lean input differs from frozen JSON"
        print("Frozen JSON -> Lean literals: exact deterministic match")
    else:
        target.write_text(expected)
        print(target)


if __name__ == "__main__":
    main()
