"""Generate untrusted finite grouping tables; Lean checks actual frozen geometry.

The old motif certificate supplies stable IDs and proposed forcing traces only.
Every geometric fact is rechecked using the complete signed ports in Lean.
Run with uv; --check verifies deterministic reproduction.
"""
import argparse
import json
from pathlib import Path
from generate_certificates import construction, rotations, move_cube, move_solid, add, scale, fitting
from generate_input import vec

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / 'strong/audit/motif_grouping_certificate.json'


def render():
    data = json.loads(SOURCE.read_text())
    fine, _ = construction()
    rots = rotations()
    contacts = data['contact_table']
    def placed(c):
        r = tuple(tuple(c['rotation'][3*k:3*k+3]) for k in range(3))
        t = tuple(c['center'])
        cs, fs = move_solid(r, fine)
        return ([add(q,t) for q in cs], [(add(f,scale(2,t)),n,[(add(p,scale(16,t)),k,u,v) for p,k,u,v in ps]) for f,n,ps in fs])
    solids = [placed(c) for c in contacts]
    indices = [next(j for j,(f,n,_) in enumerate(fine[1]) if f == tuple(d['center_times_2']) and n == tuple(d['normal'])) for d in data['face_table']]
    conflicts = []
    for i,(cs,fs) in enumerate(solids):
        row = []
        for j,(ds,gs) in enumerate(solids):
            if i == j:
                row.append(None); continue
            overlap = next(((a,b) for a,c in enumerate(cs) for b,d in enumerate(ds) if c == d),None)
            if overlap:
                row.append(('overlap',*overlap)); continue
            mismatch = next(((a,b) for a,(f,n,ps) in enumerate(fs) for b,(g,m,qs) in enumerate(gs) if f==g and n==scale(-1,m) and not fitting(ps,qs,(0,0,0))),None)
            row.append(('mismatch',*mismatch) if mismatch else None)
        conflicts.append(row)
    lines = ['-- Generated by formal/generate_grouping.py; finite claims are kernel-checked.', 'import Chair.Tiling', '', 'namespace Chair.GroupingData', '', 'set_option maxHeartbeats 0', 'set_option maxRecDepth 100000', 'set_option Elab.async false', '', 'abbrev ContactId := Fin 44', 'abbrev FaceId := Fin 24', '']
    def function(name,typ,values):
        lines.append(f'def {name} (i : Fin {len(values)}) : {typ} := match i.val with')
        lines.extend(f'  | {i} => {v}' for i,v in enumerate(values))
        lines.extend([f'  | _ => {values[0]}',''])
    def lst(xs): return '['+', '.join(map(str,xs))+']'
    function('contactOrientation','Fin 24',[str(rots.index(tuple(tuple(c['rotation'][3*k:3*k+3]) for k in range(3)))) for c in contacts])
    function('contactShift','V3',[vec(c['center']) for c in contacts])
    lines += ['theorem rotation_mem (r : Fin 24) : rotation r ∈ rotations := by', '  exact List.getElem_mem (by simpa only [rotations_length] using r.isLt)', '', 'def contactMotion (i : ContactId) : GridMotion :=', '  ⟨contactShift i, ⟨rotation (contactOrientation i), rotation_mem _⟩⟩', '']
    function('faceIndex','Fin 24',list(map(str,indices)))
    lines += ['private theorem cached_face_length : cachedFine.faces.length = 24 := by decide +kernel', '', 'def contactFace (f : FaceId) : Face :=', '  cachedFine.faces[(faceIndex f).val]\'(by rw [cached_face_length]; exact (faceIndex f).isLt)', '', 'theorem contactFace_mem (f : FaceId) : contactFace f ∈ fine.faces := by', '  rw [fine_eq_cached]', '  exact List.getElem_mem _', '']
    function('faceOptions','List ContactId',[lst([c['id'] for c in contacts if f in c['faces']]) for f in range(24)])
    lines += ['def covers (i : ContactId) (f : FaceId) : Bool := (faceOptions f).contains i', '', 'private theorem covers_checked : ∀ i : ContactId, ∀ f : FaceId,', '    covers i f = ((placed (contactMotion i)).faces.any (fun b => opposed (contactFace f) b zero)) := by', '  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]', '  decide +kernel', '', 'theorem covers_iff (i : ContactId) (f : FaceId) : covers i f = true ↔', '    ∃ b ∈ (placed (contactMotion i)).faces, Opposed (contactFace f) b zero := by', '  rw [covers_checked]', '  simp only [List.any_eq_true, opposed_eq_true]', '']
    for i,row in enumerate(conflicts):
        function(f'pairWitness{i}','Option RejectWitness',[f'some (.{x[0]} {x[1]} {x[2]})' if x else 'none' for x in row])
    function('pairWitness','ContactId → Option RejectWitness',[f'pairWitness{i}' for i in range(44)])
    lines += ['def incompatible (i j : ContactId) : Bool := (pairWitness i j).isSome', '', 'def pairAllowed (i j : ContactId) : Bool := !(incompatible i j)', '']
    for i in range(44):
        lines += [f'private theorem pair_checked_{i} : ∀ j : ContactId,', f'    (pairWitness {i} j).all (fun w => rejectCheck (placed (contactMotion {i})) (placed (contactMotion j)) zero w) = true := by', '  simp only [placed, GridMotion.solid_eq_moveSolid, fine_eq_cached]', '  decide +kernel', '']
    proof='(fun i => Fin.elim0 i)'
    for i in reversed(range(44)): proof=f'(Fin.cases pair_checked_{i} {proof})'
    lines += ['theorem pair_checked (i j : ContactId) :', '    (pairWitness i j).all (fun w => rejectCheck (placed (contactMotion i)) (placed (contactMotion j)) zero w) = true := by', '  revert j i', f'  exact {proof}', '', 'theorem incompatible_checked (i j : ContactId) (h : incompatible i j = true) :', '    ∃ w, rejectCheck (placed (contactMotion i)) (placed (contactMotion j)) zero w = true := by', '  have checked := pair_checked i j', '  unfold incompatible at h', '  cases hw : pairWitness i j with', '  | none => simp [hw] at h', '  | some w => exact ⟨w, by simpa [hw] using checked⟩', '', 'theorem incompatible_self (i : ContactId) : incompatible i i = false := by', '  revert i', '  decide +kernel', '']
    lines += ['private theorem accepted_checked : ∀ r : Fin 24,', '    (fineAccepted r).all (fun t => (List.finRange 44).any (fun i =>', '      decide ((contactMotion i).shift = t ∧ (contactMotion i).frame.mat = rotation r))) = true := by', '  decide +kernel', '', 'theorem accepted_motion (r : Fin 24) (t : V3) (ht : t ∈ fineAccepted r) :', '    ∃ i : ContactId, (contactMotion i).shift = t ∧', '      (contactMotion i).frame.mat = rotation r := by', '  have h := (List.all_eq_true.mp (accepted_checked r)) t ht', '  obtain ⟨i, _, hi⟩ := List.any_eq_true.mp h', '  exact ⟨i, of_decide_eq_true hi⟩', '']
    excluded=[w['candidate'] for b in data['pruning'] for w in b]
    triggers=list(map(int,data['trigger_propagation']))
    central=data['trigger_propagation'][str(triggers[0])]['neighborhood']
    for name,ids in [('excluded',excluded),('surviving',[i for i in range(44) if i not in excluded]),('triggers',triggers),('central',central),('notch',list(range(31,38))),('outer',[i for i in central if i !=37])]:
        lines += [f'def {name} : List ContactId := {lst(ids)}','']
    exfaces={w['candidate']:w['unfillable_face'] for b in data['pruning'] for w in b}
    function('exclusionFace','FaceId',[str(exfaces.get(i,0)) for i in range(44)])
    function('forcingTrace','List (FaceId × ContactId)',[lst([f'({s["face"]}, {s["forced_candidate"]})' for s in data['trigger_propagation'].get(str(i),{}).get('steps',[])]) for i in range(44)])
    lines += ['theorem exclusion_checked : ∀ i ∈ excluded,', '    (faceOptions (exclusionFace i)).all (incompatible i) = true := by', '  decide +kernel', '', 'def group : List GridMotion := GridMotion.identity :: outer.map contactMotion', '', 'theorem contactMotion_injective : ∀ i j : ContactId, contactMotion i = contactMotion j → i = j := by', '  decide +kernel', '', 'theorem outer_inverse_notch : ∀ i ∈ outer,', '    ∃ j ∈ notch, (contactMotion i).inv = contactMotion j := by', '  decide +kernel', '', 'theorem ordinary_notch_inverse_trigger : ∀ i ∈ notch, i ≠ 37 →', '    ∃ j ∈ triggers, (contactMotion i).inv = contactMotion j := by', '  decide +kernel', '', 'theorem exceptional_relative :', '    (contactMotion 37).inv.comp (contactMotion 39) = contactMotion 28 := by', '  decide +kernel', '', 'theorem exceptional_sibling :', '    (contactMotion 4).inv.comp (contactMotion 28) = contactMotion 39 := by', '  decide +kernel', '', 'theorem same_notch_inverse : (contactMotion 37).inv = contactMotion 4 := by decide +kernel', '', 'theorem outer_inverse_notch_nonidentity : ∀ i ∈ outer, i ≠ 4 →', '    ∃ j ∈ notch, j ≠ 37 ∧ (contactMotion i).inv = contactMotion j := by', '  decide +kernel', '', 'theorem group_nodup : group.Nodup := by decide +kernel', 'theorem group_length : group.length = 8 := by decide +kernel', '', 'theorem group_matches_frozen : (group.map GridMotion.toPlacement).Perm Input.children := by', '  decide +kernel', '', 'end Chair.GroupingData', '']
    return '\n'.join(lines)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    content=render(); path=HERE/'Chair/GroupingData.lean'
    if args.check:
        assert path.read_text()==content, f'Stale generated file: {path}'
    else: path.write_text(content)
    print('Grouping tables: deterministic match' if args.check else 'Generated grouping tables and actual-port witness checks')

if __name__=='__main__': main()
