const assert=require('node:assert/strict'),{firefox}=require('/tmp/kanpo-review-browser/node_modules/playwright');
(async()=>{const b=await firefox.launch({headless:true,executablePath:'/tmp/kanpo-review-browser/browsers/firefox-1543/firefox/firefox'});try{const c=await b.newContext({offline:true,viewport:{width:390,height:700}}),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///home/vierbein/playground/Cowork/aperiodic-chair-lab/docs/assembly.html?lang=en#rules');
for(let i=0;i<50;i++){await p.keyboard.press('Tab');assert(await p.evaluate(()=>!!document.activeElement.closest('#rule-lab')),'Tab escaped dialog');}
await p.locator('#rule-tab-1').click();await p.locator('#rule-depth').focus();await p.keyboard.press('End');assert.equal(await p.locator('#rule-depth-value').innerText(),'+24');await p.locator('#rule-flip').click();await p.locator('#rule-depth').focus();await p.keyboard.press('Home');assert.equal(await p.locator('#rule-depth-value').innerText(),'-1');await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#rule-depth-value').innerText(),'-2');
await p.locator('#rule-family').focus();await p.keyboard.press('ArrowDown');await p.keyboard.press('Enter');assert.equal(await p.locator('#rule-family').inputValue(),'2');assert.equal(await p.locator('#rule-depth-value').innerText(),'+2');
const lab=await p.evaluate(()=>ChairRuleExperiment.snapshot());await p.keyboard.press('Escape');await p.locator('#rule-open').click();assert.deepEqual(await p.evaluate(()=>ChairRuleExperiment.snapshot()),lab);
await p.locator('#rule-tab-2').click();await p.locator('#rule-profile-0').click();await p.locator('#rule-tab-0').click();await p.locator('#rule-edge-all').click();assert((await p.locator('#rule-freedom').innerText()).includes('48 → 1'));
await p.locator('#rule-tab-1').click();assert.equal(await p.locator('#rule-values button').count(),4);await p.locator('#rule-six').click();assert.equal(await p.locator('#rule-values button').count(),12);assert.equal(await p.locator('#rule-family').inputValue(),'1');
assert.deepEqual(errors,[]);console.log('PASS: 50-step keyboard focus trap, native range negative edits, native family selection, close/reopen persistence, profile 0 48-node graph, preset 4→12-family reset, offline without page errors');await c.close();}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
